---
- hosts: glusts
  become: True
 
  vars:
    glusterfs_selinux_local_policies:
      - my-glusterfsd
      - my-glusterepoll0

    # A list of bricks and their properties.
    glusterfs_bricks:
      - name: brick1
        device: /dev/vda
        mountpoint: /data/brick1

    # A list of volumes and their properties.
    glusterfs_volumes:
      - name: gv0
        bricks: /data/brick1/gv0
        replicas: 3
        mountpoint: /mnt/gv0
        rebalance: no

  roles:
    - glustersetup
