- name: Install nfs-ganesha-gluster
  ansible.builtin.package:
    name: "nfs-ganesha-gluster"
    state: present

- name: Install nfs-utils
  ansible.builtin.package:
    name: "nfs-ganesha-gluster"
    state: present

- name: populate ganesha config
  ansible.builtin.template:
    src: ../files/ganesha.conf.j2
    dest: /etc/ganesha/ganesha.conf
    owner: root
    group: root
    mode: '0600'

- name: Start and enable nfs-ganesha
  ansible.builtin.service:
    name: nfs-ganesha
    state: started
    enabled: yes

- name: Install storhaug-nfs
  ansible.builtin.package:
    name: "storhaug-nfs"
    state: present

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: /etc/sysconfig/storhaug.d/secret.pem
  run_once: yes
  register: pub_key

- name: print all returned values
  debug:
    msg: "{{ pub_key }}"