- name: Install nfs-ganesha-gluster
  ansible.builtin.package:
    name: "nfs-ganesha-gluster"
    state: present

- name: populate ganesha config
  ansible.builtin.template:
    src: ../files/ganesha.conf.j2
    dest: /etc/ganesha/ganesha.conf
    owner: root
    group: root
    mode: '0600'

- name: Start and enable nfs-ganesha
  ansible.builtin.service:
    name: nfs-ganesha
    state: started
    enabled: yes