- name: Install nfs-ganesha-gluster
  ansible.builtin.package:
    name: "nfs-ganesha-gluster"
    state: present

- name: Install nfs-utils
  ansible.builtin.package:
    name: "nfs-ganesha-gluster"
    state: present

- name: populate ganesha config
  ansible.builtin.template:
    src: ../files/ganesha.conf.j2
    dest: /etc/ganesha/ganesha.conf
    owner: root
    group: root
    mode: '0600'

- name: Start and enable nfs-ganesha
  ansible.builtin.service:
    name: nfs-ganesha
    state: started
    enabled: yes

- name: Install ctdb
  ansible.builtin.package:
    name: "ctdb"
    state: present

- name: populate ganesha config
  ansible.builtin.template:
    src: ../files/ctdb.j2
    dest: /etc/sysconfig/ctdb
    owner: root
    group: root
    mode: '0600'

- name: populate ganesha config
  ansible.builtin.template:
    src: ../files/public_addresses.j2
    dest: /etc/ctdb/public_addresses
    owner: root
    group: root
    mode: '0600'

- name: populate ganesha config
  ansible.builtin.template:
    src: ../files/nodes.j2
    dest: /etc/ctdb/nodes
    owner: root
    group: root
    mode: '0600'